<?php

return [
  [
    "id"      => "rai1",
    "code"    => "0yqrzvy5g4n",
    "name"    => "Rai 1",
    "tvgLogo" => "217",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "rai2",
    "code"    => "308718",
    "name"    => "Rai 2",
    "tvgLogo" => "218",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "rai3",
    "code"    => "308709",
    "name"    => "Rai 3",
    "tvgLogo" => "219",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "rai4",
    "code"    => "746966",
    "name"    => "Rai 4",
    "tvgLogo" => "220",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "rai5",
    "code"    => "395276",
    "name"    => "Rai 5",
    "tvgLogo" => "221",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiMovie",
    "code"    => "747002",
    "name"    => "Rai Movie",
    "tvgLogo" => "229",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiPremium",
    "code"    => "746992",
    "name"    => "Rai Premium",
    "tvgLogo" => "225",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiGulp",
    "code"    => "746953",
    "name"    => "Rai Gulp",
    "tvgLogo" => "228",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiYoyo",
    "code"    => "746899",
    "name"    => "Rai Yoyo",
    "tvgLogo" => "227",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiNews24",
    "code"    => "1",
    "name"    => "Rai News 24",
    "tvgLogo" => "222",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiStoria",
    "code"    => "746990",
    "name"    => "Rai Storia",
    "tvgLogo" => "226",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiSport",
    "code"    => "358071",
    "name"    => "Rai Sport",
    "tvgLogo" => "224",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiSportPiuHd",
    "code"    => "358025",
    "name"    => "Rai Sport +",
    "tvgLogo" => "223",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiScuola",
    "code"    => "747011",
    "name"    => "Rai Scuola",
    "tvgLogo" => "230",
    "tvgName" => "",
    "tvgId"   => "",
  ],
  [
    "id"      => "raiRadio2",
    "code"    => "747011",
    "name"    => "Rai Radio 2",
    "tvgLogo" => "https://upload.wikimedia.org/wikipedia/commons/b/bd/Rai_Radio_2_logo_%282010%29.svg",
    "tvgName" => "",
    "tvgId"   => "",
  ]
];
